cwd: /home/uend/apps/donortrust_production/current/
log_file: /home/uend/apps/donortrust_production/shared/log/mongrel.log
port: "8000"
environment: production
address: 0.0.0.0
pid_file: /home/uend/apps/donortrust_production/shared/pids/mongrel.pid
servers: 3
