--- 
cwd: /home/dtrust/donortrust/current/
log_file: /home/dtrust/donortrust/shared/log/mongrel.log
port: "8000"
environment: staging
address: web
pid_file: /home/dtrust/donortrust/shared/pids/mongrel.pid
servers: 3
